In [1]:
import pandas as pd
import scipy.stats
import numpy as np

In [2]:
paf = 'C:/Maxim/!GCCM/'
seazone = 4
year = 2018

In [3]:
if seazone == 0:
    season = 'yy'
    ss = 'yJ-annual'
else:
    season = 's' + str(seazone)
    if season == 's1':
        ss = 's1-Winter'
        ma = 'm12'
        mb = 'm1'
        mc = 'm2'
    if season == 's2':
        ss = 's2-Spring' 
        ma = 'm3'
        mb = 'm4'
        mc = 'm5'
    if season == 's3':
        ss = 's3-Summer'
        ma = 'm6'
        mb = 'm7'
        mc = 'm8'
    if season == 's4':
        ss = 's4-Autumn' 
        ma = 'm9'
        mb = 'm10'
        mc = 'm11'
        
ye = year % 100

path = paf + 'Bulletin' + str(ye) + '/' + ss

In [4]:
def Table1_1():
    igce = pd.read_table(path + '/3-Global/res_dat/' + season + '_GNS_igce.dat',\
                     sep = '\s+')
    cru = pd.read_table(path + '/3-Global/res_dat/' + season + '_GNS_cru.dat',\
                     sep = '\s+')
    
    igce.columns = ['y', 'gl_s', 'nh_s', 'sh_s', 'gl_m-1', 'nh_m-1', 'sh_m-1', 'gl_m', 'nh_m', 'sh_m', 'gl_m+1', 'nh_m+1', 'sh_m+1']
    cru.columns = ['y', 'gl_s', 'nh_s', 'sh_s', 'gl_m-1', 'nh_m-1', 'sh_m-1', 'gl_m', 'nh_m', 'sh_m', 'gl_m+1', 'nh_m+1', 'sh_m+1']
    
    cru = cru[cru['y'] > 1900]
    cru = cru.apply(pd.to_numeric)
    cru = cru.reset_index(drop=True)
    
    index = pd.MultiIndex.from_product([['1976' + '-' + str(year) + ' ' + season, '1919' + '-' + str(year) + ' ' + season], ['Gl', 'Nh', 'Sh']])
    columns = ['Corr(igce, cru)', 'e_dif', 'S_dif', 'e(abs_dif)', 'max(abs_dif)', 'b_dif*10', 'S_igce', 'S_cru', 'S(igce+cru)', 'max_dif']
    df = pd.DataFrame(index = index, columns = columns)
    
    df['Corr(igce, cru)'] = scipy.stats.pearsonr(igce['gl_s'][igce['y'] >= 1976], cru['gl_s'][cru['y'] >= 1976])[0],\
    scipy.stats.pearsonr(igce['nh_s'][igce['y'] >= 1976], cru['nh_s'][cru['y'] >= 1976])[0],\
    scipy.stats.pearsonr(igce['sh_s'][igce['y'] >= 1976], cru['sh_s'][cru['y'] >= 1976])[0],\
    scipy.stats.pearsonr(igce['gl_s'], cru['gl_s'])[0],\
    scipy.stats.pearsonr(igce['nh_s'], cru['nh_s'])[0],\
    scipy.stats.pearsonr(igce['sh_s'], cru['sh_s'])[0]
    
    dif76_Gl = igce['gl_s'][igce['y'] >= 1976] - cru['gl_s'][cru['y'] >= 1976]
    dif76_Nh = igce['nh_s'][igce['y'] >= 1976] - cru['nh_s'][cru['y'] >= 1976]
    dif76_Sh = igce['sh_s'][igce['y'] >= 1976] - cru['sh_s'][cru['y'] >= 1976]
    dif19_Gl = igce['gl_s'] - cru['gl_s']
    dif19_Nh = igce['nh_s'] - cru['nh_s']
    dif19_Sh = igce['sh_s'] - cru['sh_s']
    
    df['e_dif'] = dif76_Gl.mean(), dif76_Nh.mean(), dif76_Sh.mean(), dif19_Gl.mean(), dif19_Nh.mean(), dif19_Sh.mean()
    df['S_dif'] = dif76_Gl.std(), dif76_Nh.std(), dif76_Sh.std(), dif19_Gl.std(), dif19_Nh.std(), dif19_Sh.std()
    df['e(abs_dif)'] = dif76_Gl.abs().mean(), dif76_Nh.abs().mean(), dif76_Sh.abs().mean(),\
    dif19_Gl.abs().mean(), dif19_Nh.abs().mean(), dif19_Sh.abs().mean()
    df['max(abs_dif)'] = dif76_Gl.abs().max(), dif76_Nh.abs().max(), dif76_Sh.abs().max(),\
    dif19_Gl.abs().max(), dif19_Nh.abs().max(), dif19_Sh.abs().max()
    #df['b_dif*10'] = np.polyfit(x, y)
    df['S_igce'] = (igce['gl_s'][igce['y'] >= 1976]).std(), (igce['nh_s'][igce['y'] >= 1976]).std(), (igce['sh_s'][igce['y'] >= 1976]).std(),\
    igce['gl_s'].std(), igce['nh_s'].std(), igce['sh_s'].std()
    df['S_cru'] = (cru['gl_s'][cru['y'] >= 1976]).std(), (cru['nh_s'][cru['y'] >= 1976]).std(), (cru['sh_s'][cru['y'] >= 1976]).std(),\
    cru['gl_s'].std(), cru['nh_s'].std(), cru['sh_s'].std()
    df['S(igce+cru)'] = np.sqrt((df['S_igce'] ** 2 + df['S_cru'] ** 2) / 2)
    df['max_dif'] = dif76_Gl.max(), dif76_Nh.max(), dif76_Sh.max(), dif19_Gl.max(), dif19_Nh.max(), dif19_Sh.max()
    df = df.T
    return df

In [5]:
def Table1_2():
    igce = pd.read_table(path + '/3-Global/res_dat/' + season + '_GNS_igce.dat',\
                     sep = '\s+')
    cru = pd.read_table(path + '/3-Global/res_dat/' + season + '_GNS_cru.dat',\
                     sep = '\s+')
    
    igce.columns = ['y', 'gl_igce', 'nh_igce', 'sh_igce', 'gl_m-1', 'nh_m-1', 'sh_m-1', 'gl_m', 'nh_m', 'sh_m', 'gl_m+1', 'nh_m+1', 'sh_m+1']
    cru.columns = ['y', 'gl_cru', 'nh_cru', 'sh_cru', 'gl_m-1', 'nh_m-1', 'sh_m-1', 'gl_m', 'nh_m', 'sh_m', 'gl_m+1', 'nh_m+1', 'sh_m+1']
    
    cru = cru[cru['y'] > 1900]
    cru = cru.apply(pd.to_numeric)
    cru = cru.reset_index(drop=True)
    igce = igce[['y', 'gl_igce', 'nh_igce', 'sh_igce']]
    cru = cru[['y', 'gl_cru', 'nh_cru', 'sh_cru']]

    df = pd.DataFrame()
    df = pd.merge(igce, cru)
    df = df[df['y'] >= 2014]
    df = df.reset_index(drop=True)
    ff = pd.DataFrame()
    ff = df
    df = df.set_index('y')
    ff['y'] = ff['y'] + 1
    ff = ff.set_index('y')
    Table = pd.DataFrame()
    Table = df - ff
    Table = Table.iloc[1:len(df)]
    Table = Table.sort_index(ascending = False)
    s = Table.sum()
    Table = Table.T
    Table['2014'] = s
    Table = Table.T
    Table['y'] = Table.index
    Table = Table.reset_index(drop=True)
    Table['y'] = Table['y'].apply(pd.to_numeric)
    Table['y2'] = Table['y'] - 1
    Table['y2'].iloc[-1] = Table['y2'].iloc[-1] + len(df)
    Table = Table[['y', 'y2', 'gl_igce', 'nh_igce', 'sh_igce', 'gl_cru', 'nh_cru', 'sh_cru']]
    return Table

In [6]:

def color_2_1(val):
    color = 'red' if val == year else 'black'
    return 'color: %s' % color

In [7]:
def Table2_1():
    yr = 'y_' + season + '.'
    
    df = pd.read_table(path + '/3-Global/res_dat/GL12_ranked.dat',\
                   sep = '\s+')
    df = df[['Regions', 'reg', 'NN', season, yr]]

    df = df[df['NN'] <= 7]

    df[['Nh', 'Nh_y']] = df[[season, yr]][df['reg'] % 3 == 2]
    df[['Sh', 'Sh_y']] = df[[season, yr]][df['reg'] % 3 == 0]
    df[[season, yr]] = df[[season, yr]][df['reg'] % 3 == 1]

    df = df.rename(columns={season: 'Gl', yr: 'Gl_y'})

    Gl = df[['NN', 'Gl' ,'Gl_y']].dropna().reset_index().drop(['index'], axis=1)
    Nh = df[['NN', 'Nh', 'Nh_y']].dropna().reset_index().drop(['index'], axis=1)
    Sh = df[['NN', 'Sh', 'Sh_y']].dropna().reset_index().drop(['index'], axis=1)

    Table = Gl
    Table['Nh'] = Nh['Nh']
    Table['Nh_y'] = Nh['Nh_y']
    Table['Sh'] = Sh['Sh']
    Table['Sh_y'] = Sh['Sh_y']

    Table = Table.style.applymap(color_2_1)
    
    return Table

In [8]:
def Table2_2():
    df = pd.read_table(path + '/4-Tables/tables/table21_v' + str(year) + '_' + season + '.dat',\
                       sep = '\s+')
    df.columns = ['Regions', 'reg', 'v_' + season, 'fpr%', 'rnk', 'ext', 'nYr.', 'v_' + ma,
       'fpr%.1', 'rnk.1', 'ext.1', 'nYr..1', 'v_' + mb, 'fpr%.2', 'rnk.2',
       'ext.2', 'nYr..2', 'v_' + mc, 'fpr%.3', 'rnk.3', 'ext.3', 'nYr..3']
    df = df[['Regions', 'reg', 'v_' + season, 'fpr%', 'v_' + ma, 'fpr%.1', 'v_' + mb, 'fpr%.2', 'v_' + mc, 'fpr%.3']]
    df['reg'] = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 18, 19, 20, 21, 16, 17, 22, 23, 24]
    df = df.sort_values(by=['reg'])
    
    return df

In [9]:
def Table2_3a():
    df = pd.read_table(path + '/2-Stations/fields/' + season + '_vfe' + str(year) + 'i.xyz',\
                     sep = '\s+')
    
    Table = pd.DataFrame()
    Table['Region'] = ['Gl', 'Nh', 'Sh', 'SP', 'SM', 'EQ', 'NM', 'NP']
    
    Table['N'] = [(df['v_' + season] != -99).sum(),\
                  (df['v_' + season][df['LAT'] >= 0] != -99).sum(),\
                  (df['v_' + season][df['LAT'] <= 0] != -99).sum(),\
                  (df['v_' + season][df['LAT'] <= -65] != -99).sum(),\
                  (df['v_' + season][(df['LAT'] <= -25) & (df['LAT'] >= -65)] != -99).sum(),\
                  (df['v_' + season][(df['LAT'] <= 25) & (df['LAT'] >= -25)] != -99).sum(),\
                  (df['v_' + season][(df['LAT'] <= 65) & (df['LAT'] >= 25)] != -99).sum(),\
                  (df['v_' + season][df['LAT'] >= 65] != -99).sum()]
    
    Table['V < 0, %'] = [((df['v_' + season] != -99) & (df['v_' + season] < 0)).sum(),\
                         ((df['v_' + season][df['LAT'] >= 0] != -99) & (df['v_' + season] < 0)).sum(),\
                         ((df['v_' + season][df['LAT'] <= 0] != -99) & (df['v_' + season] < 0)).sum(),\
                         ((df['v_' + season][df['LAT'] <= -65] != -99) & (df['v_' + season] < 0)).sum(),\
                         ((df['v_' + season][(df['LAT'] <= -25) & (df['LAT'] >= -65)] != -99) & (df['v_' + season] < 0)).sum(),\
                         ((df['v_' + season][(df['LAT'] <= 25) & (df['LAT'] >= -25)] != -99) & (df['v_' + season] < 0)).sum(),\
                         ((df['v_' + season][(df['LAT'] <= 65) & (df['LAT'] >= 25)] != -99) & (df['v_' + season] < 0)).sum(),\
                         ((df['v_' + season][df['LAT'] >= 65] != -99) & (df['v_' + season] < 0)).sum()]

    Table['V < 0, %'] = Table['V < 0, %'] * 100 / Table['N']
    
    Table['V >= 0, %'] = 100 - Table['V < 0, %']
    
    Table['X =< 5%, %'] = [((df['f_' + season] != -99) & (df['f_' + season] <= 5)).sum(),\
                           ((df['f_' + season][df['LAT'] >= 0] != -99) & (df['f_' + season] <= 5)).sum(),\
                           ((df['f_' + season][df['LAT'] <= 0] != -99) & (df['f_' + season] <= 5)).sum(),\
                           ((df['f_' + season][df['LAT'] <= -65] != -99) & (df['f_' + season] <= 5)).sum(),\
                           ((df['f_' + season][(df['LAT'] <= -25) & (df['LAT'] >= -65)] != -99) & (df['f_' + season] <= 5)).sum(),\
                           ((df['f_' + season][(df['LAT'] <= 25) & (df['LAT'] >= -25)] != -99) & (df['f_' + season] <= 5)).sum(),\
                           ((df['f_' + season][(df['LAT'] <= 65) & (df['LAT'] >= 25)] != -99) & (df['f_' + season] <= 5)).sum(),\
                           ((df['f_' + season][df['LAT'] >= 65] != -99) & (df['f_' + season] <= 5)).sum()]

    Table['X =< 5%, %'] = Table['X =< 5%, %'] * 100 / Table['N']
    
    Table['X >= 95%, %'] = [((df['f_' + season] != -99) & (df['f_' + season] >= 95)).sum(),\
                            ((df['f_' + season][df['LAT'] >= 0] != -99) & (df['f_' + season] >= 95)).sum(),\
                            ((df['f_' + season][df['LAT'] <= 0] != -99) & (df['f_' + season] >= 95)).sum(),\
                            ((df['f_' + season][df['LAT'] <= -65] != -99) & (df['f_' + season] >= 95)).sum(),\
                            ((df['f_' + season][(df['LAT'] <= -25) & (df['LAT'] >= -65)] != -99) & (df['f_' + season] >= 95)).sum(),\
                            ((df['f_' + season][(df['LAT'] <= 25) & (df['LAT'] >= -25)] != -99) & (df['f_' + season] >= 95)).sum(),\
                            ((df['f_' + season][(df['LAT'] <= 65) & (df['LAT'] >= 25)] != -99) & (df['f_' + season] >= 95)).sum(),\
                            ((df['f_' + season][df['LAT'] >= 65] != -99) & (df['f_' + season] >= 95)).sum()]

    Table['X >= 95%, %'] = Table['X >= 95%, %'] * 100 / Table['N']
    
    Table['Xmin, %'] = [((df['ex_' + season] != -99) & (df['ex_' + season] < 0)).sum(),\
                        ((df['ex_' + season][df['LAT'] >= 0] != -99) & (df['ex_' + season] < 0)).sum(),\
                        ((df['ex_' + season][df['LAT'] <= 0] != -99) & (df['ex_' + season] < 0)).sum(),\
                        ((df['ex_' + season][df['LAT'] <= -65] != -99) & (df['ex_' + season] < 0)).sum(),\
                        ((df['ex_' + season][(df['LAT'] <= -25) & (df['LAT'] >= -65)] != -99) & (df['ex_' + season] < 0)).sum(),\
                        ((df['ex_' + season][(df['LAT'] <= 25) & (df['LAT'] >= -25)] != -99) & (df['ex_' + season] < 0)).sum(),\
                        ((df['ex_' + season][(df['LAT'] <= 65) & (df['LAT'] >= 25)] != -99) & (df['ex_' + season] < 0)).sum(),\
                        ((df['ex_' + season][df['LAT'] >= 65] != -99) & (df['ex_' + season] < 0)).sum()]

    Table['Xmin, %'] = Table['Xmin, %'] * 100 / Table['N']
    
    Table['Xmax, %'] = [((df['ex_' + season] != -99) & (df['ex_' + season] > 0)).sum(),\
                        ((df['ex_' + season][df['LAT'] >= 0] != -99) & (df['ex_' + season] > 0)).sum(),\
                        ((df['ex_' + season][df['LAT'] <= 0] != -99) & (df['ex_' + season] > 0)).sum(),\
                        ((df['ex_' + season][df['LAT'] <= -65] != -99) & (df['ex_' + season] > 0)).sum(),\
                        ((df['ex_' + season][(df['LAT'] <= -25) & (df['LAT'] >= -65)] != -99) & (df['ex_' + season] > 0)).sum(),\
                        ((df['ex_' + season][(df['LAT'] <= 25) & (df['LAT'] >= -25)] != -99) & (df['ex_' + season] > 0)).sum(),\
                        ((df['ex_' + season][(df['LAT'] <= 65) & (df['LAT'] >= 25)] != -99) & (df['ex_' + season] > 0)).sum(),\
                        ((df['ex_' + season][df['LAT'] >= 65] != -99) & (df['ex_' + season] > 0)).sum()]

    Table['Xmax, %'] = Table['Xmax, %'] * 100 / Table['N']
    
    return Table

In [10]:
def Table2_3b():
    df = pd.read_table(path + '/1-HadCRU/fields/' + season + '_vfe' + str(year) + 'hc.xyz',\
                     sep = '\s+')
    
    Table = pd.DataFrame()
    Table['Region'] = ['Gl', 'Nh', 'Sh', 'SP', 'SM', 'EQ', 'NM', 'NP']
    
    Table['N'] = [(df['v_' + season] != -99).sum(),\
                  (df['v_' + season][df['LAT'] >= 0] != -99).sum(),\
                  (df['v_' + season][df['LAT'] <= 0] != -99).sum(),\
                  (df['v_' + season][df['LAT'] <= -65] != -99).sum(),\
                  (df['v_' + season][(df['LAT'] <= -25) & (df['LAT'] >= -65)] != -99).sum(),\
                  (df['v_' + season][(df['LAT'] <= 25) & (df['LAT'] >= -25)] != -99).sum(),\
                  (df['v_' + season][(df['LAT'] <= 65) & (df['LAT'] >= 25)] != -99).sum(),\
                  (df['v_' + season][df['LAT'] >= 65] != -99).sum()]
    
    Table['V < 0, %'] = [((df['v_' + season] != -99) & (df['v_' + season] < 0)).sum(),\
                         ((df['v_' + season][df['LAT'] >= 0] != -99) & (df['v_' + season] < 0)).sum(),\
                         ((df['v_' + season][df['LAT'] <= 0] != -99) & (df['v_' + season] < 0)).sum(),\
                         ((df['v_' + season][df['LAT'] <= -65] != -99) & (df['v_' + season] < 0)).sum(),\
                         ((df['v_' + season][(df['LAT'] <= -25) & (df['LAT'] >= -65)] != -99) & (df['v_' + season] < 0)).sum(),\
                         ((df['v_' + season][(df['LAT'] <= 25) & (df['LAT'] >= -25)] != -99) & (df['v_' + season] < 0)).sum(),\
                         ((df['v_' + season][(df['LAT'] <= 65) & (df['LAT'] >= 25)] != -99) & (df['v_' + season] < 0)).sum(),\
                         ((df['v_' + season][df['LAT'] >= 65] != -99) & (df['v_' + season] < 0)).sum()]

    Table['V < 0, %'] = Table['V < 0, %'] * 100 / Table['N']
    
    Table['V >= 0, %'] = 100 - Table['V < 0, %']
    
    Table['X =< 5%, %'] = [((df['f_' + season] != -99) & (df['f_' + season] <= 5)).sum(),\
                           ((df['f_' + season][df['LAT'] >= 0] != -99) & (df['f_' + season] <= 5)).sum(),\
                           ((df['f_' + season][df['LAT'] <= 0] != -99) & (df['f_' + season] <= 5)).sum(),\
                           ((df['f_' + season][df['LAT'] <= -65] != -99) & (df['f_' + season] <= 5)).sum(),\
                           ((df['f_' + season][(df['LAT'] <= -25) & (df['LAT'] >= -65)] != -99) & (df['f_' + season] <= 5)).sum(),\
                           ((df['f_' + season][(df['LAT'] <= 25) & (df['LAT'] >= -25)] != -99) & (df['f_' + season] <= 5)).sum(),\
                           ((df['f_' + season][(df['LAT'] <= 65) & (df['LAT'] >= 25)] != -99) & (df['f_' + season] <= 5)).sum(),\
                           ((df['f_' + season][df['LAT'] >= 65] != -99) & (df['f_' + season] <= 5)).sum()]

    Table['X =< 5%, %'] = Table['X =< 5%, %'] * 100 / Table['N']
    
    Table['X >= 95%, %'] = [((df['f_' + season] != -99) & (df['f_' + season] >= 95)).sum(),\
                            ((df['f_' + season][df['LAT'] >= 0] != -99) & (df['f_' + season] >= 95)).sum(),\
                            ((df['f_' + season][df['LAT'] <= 0] != -99) & (df['f_' + season] >= 95)).sum(),\
                            ((df['f_' + season][df['LAT'] <= -65] != -99) & (df['f_' + season] >= 95)).sum(),\
                            ((df['f_' + season][(df['LAT'] <= -25) & (df['LAT'] >= -65)] != -99) & (df['f_' + season] >= 95)).sum(),\
                            ((df['f_' + season][(df['LAT'] <= 25) & (df['LAT'] >= -25)] != -99) & (df['f_' + season] >= 95)).sum(),\
                            ((df['f_' + season][(df['LAT'] <= 65) & (df['LAT'] >= 25)] != -99) & (df['f_' + season] >= 95)).sum(),\
                            ((df['f_' + season][df['LAT'] >= 65] != -99) & (df['f_' + season] >= 95)).sum()]

    Table['X >= 95%, %'] = Table['X >= 95%, %'] * 100 / Table['N']
    
    Table['Xmin, %'] = [((df['ex_' + season] != -99) & (df['ex_' + season] < 0)).sum(),\
                        ((df['ex_' + season][df['LAT'] >= 0] != -99) & (df['ex_' + season] < 0)).sum(),\
                        ((df['ex_' + season][df['LAT'] <= 0] != -99) & (df['ex_' + season] < 0)).sum(),\
                        ((df['ex_' + season][df['LAT'] <= -65] != -99) & (df['ex_' + season] < 0)).sum(),\
                        ((df['ex_' + season][(df['LAT'] <= -25) & (df['LAT'] >= -65)] != -99) & (df['ex_' + season] < 0)).sum(),\
                        ((df['ex_' + season][(df['LAT'] <= 25) & (df['LAT'] >= -25)] != -99) & (df['ex_' + season] < 0)).sum(),\
                        ((df['ex_' + season][(df['LAT'] <= 65) & (df['LAT'] >= 25)] != -99) & (df['ex_' + season] < 0)).sum(),\
                        ((df['ex_' + season][df['LAT'] >= 65] != -99) & (df['ex_' + season] < 0)).sum()]

    Table['Xmin, %'] = Table['Xmin, %'] * 100 / Table['N']
    
    Table['Xmax, %'] = [((df['ex_' + season] != -99) & (df['ex_' + season] > 0)).sum(),\
                        ((df['ex_' + season][df['LAT'] >= 0] != -99) & (df['ex_' + season] > 0)).sum(),\
                        ((df['ex_' + season][df['LAT'] <= 0] != -99) & (df['ex_' + season] > 0)).sum(),\
                        ((df['ex_' + season][df['LAT'] <= -65] != -99) & (df['ex_' + season] > 0)).sum(),\
                        ((df['ex_' + season][(df['LAT'] <= -25) & (df['LAT'] >= -65)] != -99) & (df['ex_' + season] > 0)).sum(),\
                        ((df['ex_' + season][(df['LAT'] <= 25) & (df['LAT'] >= -25)] != -99) & (df['ex_' + season] > 0)).sum(),\
                        ((df['ex_' + season][(df['LAT'] <= 65) & (df['LAT'] >= 25)] != -99) & (df['ex_' + season] > 0)).sum(),\
                        ((df['ex_' + season][df['LAT'] >= 65] != -99) & (df['ex_' + season] > 0)).sum()]

    Table['Xmax, %'] = Table['Xmax, %'] * 100 / Table['N']
    
    return Table

In [11]:
def Table2_4():
    
    df = pd.read_table(path + '/4-Tables/res_st/stat39msy.dat',\
                       sep = '\s+')
    
    df = df[df['reg'] <= 27]
    mask = (df['st'] == 1) | (df['st'] == 4)
    df = df.loc[mask]
    df = df.sort_values(by=['st'])
    df = df.drop(['stat', 'm00'], axis = 1)
    
    df1 = pd.DataFrame()
    df4 = pd.DataFrame()
    Table = pd.DataFrame()
    
    df1 = df[df['st'] == 1].sort_values(by=['reg']).reset_index(drop=True)
    df4 = df[df['st'] == 4].sort_values(by=['reg']).reset_index(drop=True)
    
    for column in df1:
        try:
            df1[column].apply(pd.to_numeric)
        except:
            df1 = df1.drop([column], axis = 1)          
            
    df1.iloc[:, 2:] = df1.iloc[:, 2:] / 1000
    
    for column in df4:
        try:
            df4[column].apply(pd.to_numeric)
        except:
            df4 = df4.drop([column], axis = 1)          
    
    df4.iloc[:, 2:] = df4.iloc[:, 2:] // 100  
    
    
    Table['reg'] = df1['reg']
    
    df1 = df1.drop(['reg'], axis = 1)
    df1 = df1.drop(['st'], axis = 1)
    df4 = df4.drop(['reg'], axis = 1)
    df4 = df4.drop(['st'], axis = 1)
    
    for i in df1:
        Table[i + '_1'] = df1[i]
        Table[i + '_4'] = df4[i]
    
    return Table

In [12]:
def Table3_1(): 
       
    df76 = pd.read_table(path + '/4-Tables/tables/table31_b76'+ str(ye) + '_' + season + '.dat',\
                         sep = '\s+')
    df19 = pd.read_table(path + '/4-Tables/tables/table31_b19'+ str(ye) + '_' + season + '.dat',\
                         sep = '\s+')    
    df76.columns = ['Regions', 'reg', 'season_76', '_al%', '_d%_', 'NYr.', 'm-1_76',
       '_al%.1', '_d%_.1', 'NYr..1', 'm_76', '_al%.2', '_d%_.2', 'NYr..2',
       'm+1_76', '_al%.3', '_d%_.3', 'NYr..3']    
    df19.columns = ['Regions', 'reg', 'season_19', '_al%', '_d%_', 'NYr.', 'm-1_19',
       '_al%.1', '_d%_.1', 'NYr..1', 'm_19', '_al%.2', '_d%_.2', 'NYr..2',
       'm+1_19', '_al%.3', '_d%_.3', 'NYr..3']    
    df = pd.DataFrame()
    
    df['Regions'] = df76['Regions']
    df['reg'] = df76['reg']
    df[season + '_76'] = df76['season_76']
    df[ma + '_76'] = df76['m-1_76']
    df[mb + '_76'] = df76['m_76']
    df[mc + '_76'] = df76['m+1_76']
    df[season + '_19'] = df19['season_19']
    df[ma + '_19'] = df19['m-1_19']
    df[mb + '_19'] = df19['m_19']
    df[mc + '_19'] = df19['m+1_19']
    
    return df

In [13]:
'''
def Table3_2():
    df = Table3_1()
    kf = Table3_1()
    Table = pd.DataFrame()
    Shmable = pd.DataFrame()
    
    if seazone != 0:               
        df = df.T
        df = df.drop(['Regions', 'reg'])
        Table['T3288/HSST_Gl'] = df[3] / df[9]
        Table['T3288/HSST_Nh'] = df[4] / df[10]
        Table['T3288/HSST_Sh'] = df[5] / df[11]
        Table['CRUTEM/HSST_Gl'] = df[6] / df[9]
        Table['CRUTEM/HSST_Nh'] = df[7] / df[10]
        Table['CRUTEM/HSST_Sh'] = df[8] / df[11]
        Table['Nh/Sh_HadCRUT'] = df[1] / df[2]
        Table['Nh/Sh_igce'] = df[4] / df[5]
        Table['Nh/Sh_CRUTEM'] = df[7] / df[8]
        Table['Nh/Sh_HSST'] = df[10] / df[11]
        Table = Table.T
        
        kf = kf.drop([0, 3, 6, 9])
        kf[season] = kf[season+ '_76'] / kf[season + '_19']
        kf[ma] = kf[ma + '_76'] / kf[ma + '_19']
        kf[mb] = kf[mb + '_76'] / kf[mb + '_19']
        kf[mc] = kf[mc + '_76'] / kf[mc + '_19']
        kf = kf[['Regions', 'reg', season, ma, mb, mc]]
        kf = kf.T
        kf = kf[[1, 4, 7, 10, 2, 5, 8, 11]]
        return Table, kf.iloc[:4], kf.iloc[5:]
'''

"\ndef Table3_2():\n    df = Table3_1()\n    kf = Table3_1()\n    Table = pd.DataFrame()\n    Shmable = pd.DataFrame()\n    \n    if seazone != 0:               \n        df = df.T\n        df = df.drop(['Regions', 'reg'])\n        Table['T3288/HSST_Gl'] = df[3] / df[9]\n        Table['T3288/HSST_Nh'] = df[4] / df[10]\n        Table['T3288/HSST_Sh'] = df[5] / df[11]\n        Table['CRUTEM/HSST_Gl'] = df[6] / df[9]\n        Table['CRUTEM/HSST_Nh'] = df[7] / df[10]\n        Table['CRUTEM/HSST_Sh'] = df[8] / df[11]\n        Table['Nh/Sh_HadCRUT'] = df[1] / df[2]\n        Table['Nh/Sh_igce'] = df[4] / df[5]\n        Table['Nh/Sh_CRUTEM'] = df[7] / df[8]\n        Table['Nh/Sh_HSST'] = df[10] / df[11]\n        Table = Table.T\n        \n        kf = kf.drop([0, 3, 6, 9])\n        kf[season] = kf[season+ '_76'] / kf[season + '_19']\n        kf[ma] = kf[ma + '_76'] / kf[ma + '_19']\n        kf[mb] = kf[mb + '_76'] / kf[mb + '_19']\n        kf[mc] = kf[mc + '_76'] / kf[mc + '_19']\n        kf = kf[['Regions', 'reg', season, ma, mb, mc]]\n        kf = kf.T\n        kf = kf[[1, 4, 7, 10, 2, 5, 8, 11]]\n        return Table, kf.iloc[:4], kf.iloc[5:]\n"

In [14]:
'''
def color_4_1(val):
    color = 'red' if val == year else 'black'
    return 'color: %s' % color
'''

"\ndef color_4_1(val):\n    color = 'red' if val == year else 'black'\n    return 'color: %s' % color\n"

In [15]:
def Table4_1():    
    df = pd.read_table(path + '/4-Tables/tables/table41_b76' + str(ye) + '_' + season + '.dat',\
                   sep = '\s+')
    #df = df.style.applymap(color_4_1)
    df = df[['Regions', 'reg', season + '_b76' + str(ye), ma + '_b76' + str(ye), mb + '_b76' + str(ye), mc + '_b76' + str(ye)]]
    return df

In [16]:
def Table4_2():
    
    df = pd.read_table(path + '/4-Tables/res_st/stat39msy.dat',\
                       sep = '\s+')
    
    df = df[df['reg'] >= 13]
    df = df[df['reg'] <= 27]
    mask = (df['st'] == 7) | (df['st'] == 9)
    df = df.loc[mask]
    df = df.sort_values(by=['st'])
    df = df.drop(['stat', 'm00'], axis = 1)
    
    df7 = pd.DataFrame()
    df9 = pd.DataFrame()
    Table = pd.DataFrame()
    
    df7 = df[df['st'] == 7].sort_values(by=['reg']).reset_index(drop=True)
    df9 = df[df['st'] == 9].sort_values(by=['reg']).reset_index(drop=True)         
            
    df7.iloc[:, 2:] = df7.iloc[:, 2:].apply(pd.to_numeric) / 1000      
    
    df9.iloc[:, 2:] = df9.iloc[:, 2:].apply(pd.to_numeric) / 100  
    
    
    Table['reg'] = df7['reg']
    Table['_Region_'] = df7['_Region_']
    
    df7 = df7.drop(['reg'], axis = 1)
    df7 = df7.drop(['st'], axis = 1)
    df7 = df7.drop(['_Region_'], axis = 1)
    df9 = df9.drop(['reg'], axis = 1)
    df9 = df9.drop(['st'], axis = 1)
    df9 = df9.drop(['_Region_'], axis = 1)

    for i in df7:
        Table[i + '_7'] = df7[i]
        Table[i + '_9'] = df9[i]
    
    return Table

In [17]:
writer = pd.ExcelWriter('tables.xlsx')
Table1_1().to_excel(writer,'Table1.1')
Table1_2().to_excel(writer,'Table1.2')
Table2_1().to_excel(writer,'Table2.1')
Table2_2().to_excel(writer,'Table2.2')
Table2_3a().to_excel(writer,'Table2.3a')
Table2_3b().to_excel(writer,'Table2.3b')
Table2_4().to_excel(writer,'Table2.4')
Table3_1().to_excel(writer,'Table3.1')
#Table3_2().to_excel(writer,'Table3.2')
Table4_1().to_excel(writer,'Table4.1')
Table4_2().to_excel(writer,'Table4.2')
writer.save()

C:\Users\igce\Anaconda3\lib\site-packages\pandas\core\indexing.py:189: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self._setitem_with_indexer(indexer, value)

In [ ]:
ПОПЫТКА РАСКРАСИТЬ 4.1

In [44]:
df = pd.read_table(path + '/4-Tables/tables/table41_b76' + str(ye) + '_' + season + '.dat',\
                   sep = '\s+')

In [46]:
df.head()

,Regions,reg,s3_b7618,_al%,_d%_,NYr.,m6_b7618,_al%.1,_d%_.1,NYr..1,m7_b7618,_al%.2,_d%_.2,NYr..2,m8_b7618,_al%.3,_d%_.3,NYr..3
0,hcru.AO,13,0.201,0.0,59.4,43.0,0.180,0.0,50.3,43.0,0.188,0.0,55.1,43.0,0.234,0.0,60.7,43.0
1,hcru.PO,14,0.224,0.0,62.5,43.0,0.198,0.0,59.3,43.0,0.239,0.0,59.5,43.0,0.236,0.0,59.0,43.0
2,hcru.NP,15,0.425,0.0,70.7,43.0,0.487,0.0,61.2,43.0,0.393,0.0,60.9,43.0,0.417,0.0,66.5,43.0
3,hcru.NM,16,0.309,0.0,83.7,43.0,0.289,0.0,80.5,43.0,0.307,0.0,79.7,43.0,0.330,0.0,82.9,43.0
4,hcru.EQ,17,0.147,0.0,62.5,43.0,0.152,0.0,58.6,43.0,0.141,0.0,57.8,43.0,0.147,0.0,64.0,43.0

In [48]:
for i in range (0, len(df['_al%'])):
    if df['_al%'][i] > 0:
        df['s3_b7618'][i] = str(df['s3_b7618'][i]) + '**'

-c:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [49]:
df['s3_b7618']

0                      0.201
1                      0.224
2                      0.425
3                      0.309
4                      0.147
5                      0.114
6      0.10300000000000001**
7                       0.27
8                      0.383
9                      0.165
10                     0.291
11                   0.177**
12    0.037000000000000005**
13                     0.526
14                     0.341
Name: s3_b7618, dtype: object